services:
  - type: web
    name: m5-demand-forecasting
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SEED_USERS
        sync: false
